apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-to-api
  namespace: client
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: client
          podSelector:
            matchLabels:
              app: netshoot
              tier: debug
      ports:
        - protocol: TCP
          port: 80
